name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: NPM setup
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Dependencies install
        run: yarn install --frozen-lockfile

      - name: Project build
        run: yarn run build
        env:
          GRIDSOME_EMAILJS_SERVICE_ID: ${{ secrets.GRIDSOME_EMAILJS_SERVICE_ID }}
          GRIDSOME_EMAILJS_TEMPLATE_ID: ${{ secrets.GRIDSOME_EMAILJS_TEMPLATE_ID }}
          GRIDSOME_EMAILJS_USER_ID: ${{ secrets.GRIDSOME_EMAILJS_USER_ID }}
          GRIDSOME_SHEET_BEST_URL: ${{ secrets.GRIDSOME_SHEET_BEST_URL }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
